[package]
name = "dna"
version = "0.1.0"
edition = "2018"
description = "A utility that takes a DNA string and transcribes it to RNA"
license = "MIT/Apache-2.0"
repository = "https://github.com/GJZwiers/birdie"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
