[package]
name = "pattern_matching"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bio = "0.37"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
